# team-a-cq.yaml
apiVersion: kueue.x-k8s.io/v1alpha2
kind: ClusterQueue
metadata:
  name: team-a-cq
spec:
  namespaceSelector: {}
  cohort: team-ab
  resources:
    - name: "cpu"
      flavors:
        - name: default
          quota:
            min: 9
            max: 15
    - name: "memory"
      flavors:
        - name: default
          quota:
            min: 36Gi
            max: 60Gi
