# team-b-cq.yaml
apiVersion: kueue.x-k8s.io/v1alpha2
kind: ClusterQueue
metadata:
  name: team-b-cq
spec:
  namespaceSelector: {}
  cohort: team-ab
  resources:
    - name: "cpu"
      flavors:
        - name: default
          quota:
            min: 12
    - name: "memory"
      flavors:
        - name: default
          quota:
            min: 48Gi
